<?php

use Illuminate\Database\Seeder;

class MembersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){

        DB::table('members')->insert([
            ['name_sei' => 'test1',
            'name_mei' => 'test1',
            'nickname' => 'nickname_test1',
            'gender' => '1',
            'password' => Hash::make('my_secure_password1'),
            'email' => 'test@test1',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test2',
            'name_mei' => 'test2',
            'nickname' => 'nickname_test2',
            'gender' => '1',
            'password' => Hash::make('my_secure_password2'),
            'email' => 'test@test2',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test3',
            'name_mei' => 'test3',
            'nickname' => 'nickname_test3',
            'gender' => '1',
            'password' => Hash::make('my_secure_password3'),
            'email' => 'test@test3',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test4',
            'name_mei' => 'test4',
            'nickname' => 'nickname_test4',
            'gender' => '1',
            'password' => Hash::make('my_secure_password4'),
            'email' => 'test@test4',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test5',
            'name_mei' => 'test5',
            'nickname' => 'nickname_test5',
            'gender' => '1',
            'password' => Hash::make('my_secure_password5'),
            'email' => 'test@test5',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test6',
            'name_mei' => 'test6',
            'nickname' => 'nickname_test6',
            'gender' => '1',
            'password' => Hash::make('my_secure_password6'),
            'email' => 'test@test6',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test7',
            'name_mei' => 'test7',
            'nickname' => 'nickname_test7',
            'gender' => '1',
            'password' => Hash::make('my_secure_password7'),
            'email' => 'test@test7',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test8',
            'name_mei' => 'test8',
            'nickname' => 'nickname_test8',
            'gender' => '1',
            'password' => Hash::make('my_secure_password8'),
            'email' => 'test@test8',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test9',
            'name_mei' => 'test9',
            'nickname' => 'nickname_test9',
            'gender' => '1',
            'password' => Hash::make('my_secure_password9'),
            'email' => 'test@test9',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test10',
            'name_mei' => 'test10',
            'nickname' => 'nickname_test10',
            'gender' => '1',
            'password' => Hash::make('my_secure_password10'),
            'email' => 'test@test10',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test11',
            'name_mei' => 'test11',
            'nickname' => 'nickname_test11',
            'gender' => '1',
            'password' => Hash::make('my_secure_password11'),
            'email' => 'test@test11',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test12',
            'name_mei' => 'test12',
            'nickname' => 'nickname_test12',
            'gender' => '1',
            'password' => Hash::make('my_secure_password12'),
            'email' => 'test@test12',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test13',
            'name_mei' => 'test13',
            'nickname' => 'nickname_test13',
            'gender' => '1',
            'password' => Hash::make('my_secure_password13'),
            'email' => 'test@test13',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test14',
            'name_mei' => 'test14',
            'nickname' => 'nickname_test14',
            'gender' => '1',
            'password' => Hash::make('my_secure_password14'),
            'email' => 'test@test14',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test15',
            'name_mei' => 'test15',
            'nickname' => 'nickname_test15',
            'gender' => '1',
            'password' => Hash::make('my_secure_password15'),
            'email' => 'test@test15',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test16',
            'name_mei' => 'test16',
            'nickname' => 'nickname_test16',
            'gender' => '1',
            'password' => Hash::make('my_secure_password16'),
            'email' => 'test@test16',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test17',
            'name_mei' => 'test17',
            'nickname' => 'nickname_test17',
            'gender' => '1',
            'password' => Hash::make('my_secure_password17'),
            'email' => 'test@test17',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test18',
            'name_mei' => 'test18',
            'nickname' => 'nickname_test18',
            'gender' => '1',
            'password' => Hash::make('my_secure_password18'),
            'email' => 'test@test18',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test19',
            'name_mei' => 'test19',
            'nickname' => 'nickname_test19',
            'gender' => '1',
            'password' => Hash::make('my_secure_password19'),
            'email' => 'test@test19',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test20',
            'name_mei' => 'test20',
            'nickname' => 'nickname_test20',
            'gender' => '1',
            'password' => Hash::make('my_secure_password20'),
            'email' => 'test@test20',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test21',
            'name_mei' => 'test21',
            'nickname' => 'nickname_test21',
            'gender' => '1',
            'password' => Hash::make('my_secure_password21'),
            'email' => 'test@test21',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test22',
            'name_mei' => 'test22',
            'nickname' => 'nickname_test22',
            'gender' => '1',
            'password' => Hash::make('my_secure_password22'),
            'email' => 'test@test22',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test23',
            'name_mei' => 'test23',
            'nickname' => 'nickname_test23',
            'gender' => '1',
            'password' => Hash::make('my_secure_password23'),
            'email' => 'test@test23',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test24',
            'name_mei' => 'test24',
            'nickname' => 'nickname_test24',
            'gender' => '1',
            'password' => Hash::make('my_secure_password24'),
            'email' => 'test@test24',
            'created_at' => new DateTime(),
            ],
            ['name_sei' => 'test25',
            'name_mei' => 'test25',
            'nickname' => 'nickname_test25',
            'gender' => '1',
            'password' => Hash::make('my_secure_password25'),
            'email' => 'test@test25',
            'created_at' => new DateTime(),
            ]
            ]);
    }
}
